let colors = {
    'a': 'red',
    'b': 'indigo',
    'c': 'yellow',
    'd': 'red',
    'e': 'blue',
    'f': 'deep-orange',
    'g': 'deep-purple',
    'h': 'pink',
    'i': 'yellow',
    'j': 'indigo',
    'k': 'purple',
    'l': 'green',
    'm': 'yellow',
    'n': 'deep-purple',
    'o': 'red',
    'p': 'purple',
    'q': 'yellow',
    'r': 'cyan',
    's': 'green',
    't': 'red',
    'u': 'blue',
    'v': 'yellow',
    'w': 'deep-purple',
    'x': 'deep-orange',
    'y': 'yellow',
    'z': 'red',
};

export default colors;